In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/1_preprocessing_1_car_pricing.csv")
df.head()

,price,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,notRepairedDamage
0,6315,limousine,2000,manuell,0,80,5000,benzin,audi,nein
1,1900,kleinwagen,2003,manuell,52,matiz,70000,benzin,Other,nein
2,6000,limousine,2010,manuell,105,golf,150000,diesel,volkswagen,nein
3,10499,kombi,2008,automatik,110,clubman,100000,diesel,Other,nein
4,5500,kleinwagen,2010,automatik,54,fortwo,125000,diesel,Other,nein

# Conociendo datos

In [3]:
df.shape

(50000, 10)

In [4]:
df.head(5)

,price,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,notRepairedDamage
0,6315,limousine,2000,manuell,0,80,5000,benzin,audi,nein
1,1900,kleinwagen,2003,manuell,52,matiz,70000,benzin,Other,nein
2,6000,limousine,2010,manuell,105,golf,150000,diesel,volkswagen,nein
3,10499,kombi,2008,automatik,110,clubman,100000,diesel,Other,nein
4,5500,kleinwagen,2010,automatik,54,fortwo,125000,diesel,Other,nein

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   price               50000 non-null  int64
 1   vehicleType         50000 non-null  object
 2   yearOfRegistration  50000 non-null  int64
 3   gearbox             50000 non-null  object
 4   powerPS             50000 non-null  int64
 5   model               50000 non-null  object
 6   kilometer           50000 non-null  int64
 7   fuelType            50000 non-null  object
 8   brand               50000 non-null  object
 9   notRepairedDamage   50000 non-null  object
dtypes: int64(4), object(6)
memory usage: 3.8+ MB

In [6]:
df.describe()

               price  yearOfRegistration      powerPS      kilometer
count   50000.000000        50000.000000  50000.00000   50000.000000
mean     6315.326840         2003.418680    115.68854  125510.500000
std      8281.921478            7.513713    189.12424   40298.366827
min       500.000000         1955.000000      0.00000    5000.000000
25%      1699.000000         1999.000000     70.00000  125000.000000
50%      4000.000000         2003.000000    105.00000  150000.000000
75%      7190.000000         2008.000000    150.00000  150000.000000
max    197000.000000         2019.000000  20000.00000  150000.000000

In [7]:
df.describe(include="object")

       vehicleType  gearbox  model fuelType       brand notRepairedDamage
count        50000    50000  50000    50000       50000             50000
unique           8        2    247        7          11                 2
top      limousine  manuell   golf   benzin  volkswagen              nein
freq         18033    39562   6779    34504       10631             45069

In [8]:
df.reset_index(drop=True, inplace=True)
df.to_csv("../data/2_discovery_1_car_pricing.csv", index=False)